#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

pear install --alldeps HTTP_Request2 Net_URL2
mkdir -p $OPENSHIFT_DATA_DIR/state
chmod 777 $OPENSHIFT_DATA_DIR/state
